### ISSUE TITLE
define_reader_method  exists bug

### ISSUE THREAD

**Issue by wgui1314** [simple-and-powerful/act-form#5]
hello:
lib/act_form/attributes.rb   define_reader_method.  when value is false ,return nil

**Comment by wgui1314** [comment]
![image](https://user-images.githubusercontent.com/52034614/136742363-d2819ef1-3ad1-4513-ae3c-75014c7fdd0e.png)

**Comment by zires** [comment]
Got it, i will fix this soon

**Comment by zires** [comment]
Fixed in version 0.4.1
